"""Adds per-agent log files to ARDunning.ipynb — patches cell 9 (orchestrate)."""
import json

with open("ARDunning.ipynb", encoding="utf-8") as f:
    nb = json.load(f)

new_source = (
    '# ═══════════════════════════════════════════════════════════════\n'
    '# ORCHESTRATION  —  Orchestrator Agent  |  with per-agent logging\n'
    '# ═══════════════════════════════════════════════════════════════\n'
    '\n'
    'PARSE_LOG = OUTPUT_DIR / "ParseCustomerResponse.log"\n'
    'ERP_LOG   = OUTPUT_DIR / "AccessUpdateERP.log"\n'
    '\n'
    '\n'
    'def _append_agent_log(\n'
    '    log_path: Path,\n'
    '    agent_name: str,\n'
    '    email_file: str,\n'
    '    invoice_number: str,\n'
    '    input_text: str,\n'
    '    result: dict,\n'
    ') -> None:\n'
    '    """Append one timestamped entry to the agent\'s own log file in Output/."""\n'
    '    ts       = datetime.now().strftime("%Y-%m-%d %H:%M:%S")\n'
    '    messages = result.get("messages", [])\n'
    '\n'
    '    conversation_lines  = []\n'
    '    total_input_tokens  = 0\n'
    '    total_output_tokens = 0\n'
    '\n'
    '    for msg in messages:\n'
    '        role    = type(msg).__name__\n'
    '        content = str(msg.content) if getattr(msg, "content", None) else ""\n'
    '\n'
    '        # Accumulate token usage from AI messages (Google GenAI populates usage_metadata)\n'
    '        um = getattr(msg, "usage_metadata", None)\n'
    '        if um:\n'
    '            total_input_tokens  += getattr(um, "input_tokens",  0) or 0\n'
    '            total_output_tokens += getattr(um, "output_tokens", 0) or 0\n'
    '\n'
    '        # Format any tool calls attached to the AI message\n'
    '        tool_calls_str = ""\n'
    '        for tc in getattr(msg, "tool_calls", []):\n'
    '            tool_calls_str += f"\\n    [ToolCall] {tc[\'name\']}({json.dumps(tc[\'args\'])})"\n'
    '\n'
    '        conversation_lines.append(f"  [{role}] {content}{tool_calls_str}")\n'
    '\n'
    '    final_output = messages[-1].content if messages else "(no output)"\n'
    '\n'
    '    log_entry = (\n'
    '        "\\n" + "=" * 80 + "\\n"\n'
    '        f"TIMESTAMP      : {ts}\\n"\n'
    '        f"AGENT          : {agent_name}\\n"\n'
    '        f"EMAIL FILE     : {email_file}\\n"\n'
    '        f"INVOICE        : {invoice_number}\\n"\n'
    '        + "-" * 80 + "\\n"\n'
    '        + "INPUT:\\n"\n'
    '        + input_text + "\\n"\n'
    '        + "-" * 80 + "\\n"\n'
    '        + "CONVERSATION TRANSCRIPT:\\n"\n'
    '        + "\\n".join(conversation_lines) + "\\n"\n'
    '        + "-" * 80 + "\\n"\n'
    '        + "FINAL OUTPUT:\\n"\n'
    '        + final_output + "\\n"\n'
    '        + "-" * 80 + "\\n"\n'
    '        + "TOKEN USAGE:\\n"\n'
    '        + f"  Input tokens  : {total_input_tokens}\\n"\n'
    '        + f"  Output tokens : {total_output_tokens}\\n"\n'
    '        + f"  Total tokens  : {total_input_tokens + total_output_tokens}\\n"\n'
    '        + "=" * 80 + "\\n"\n'
    '    )\n'
    '\n'
    '    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n'
    '    with open(log_path, "a", encoding="utf-8") as fh:\n'
    '        fh.write(log_entry)\n'
    '\n'
    '\n'
    'def orchestrate() -> None:\n'
    '    """Main loop: process every email, call agents, log each call, move to Processed_Emails/."""\n'
    '    print("=" * 60)\n'
    '    print("AR DUNNING MULTI-AGENT ORCHESTRATION")\n'
    '    print("=" * 60)\n'
    '\n'
    '    parse_agent = create_parse_customer_response_agent()\n'
    '    erp_agent   = create_access_update_erp_agent()\n'
    '\n'
    '    email_files = sorted(INPUT_EMAILS_DIR.glob("*.txt"))\n'
    '    print(f"\\nFound {len(email_files)} email(s) to process.\\n")\n'
    '\n'
    '    for email_file in email_files:\n'
    "        print(f\"\\n{'─' * 50}\")\n"
    '        print(f"Processing: {email_file.name}")\n'
    "        print(f\"{'─' * 50}\")\n"
    '\n'
    '        try:\n'
    '            email_content = email_file.read_text(encoding="utf-8")\n'
    '            parse_input   = f"Process this customer email:\\n\\n{email_content}"\n'
    '\n'
    '            # ── Step 1: ParseCustomerResponse ────────────────────────────\n'
    '            parse_result = parse_agent.invoke({"messages": [("human", parse_input)]})\n'
    '            output_str   = parse_result["messages"][-1].content\n'
    '            print(f"\\nParse Agent Output:\\n{output_str}\\n")\n'
    '\n'
    '            # Extract JSON from the final response\n'
    '            parsed_data = {}\n'
    '            start = output_str.rfind("{")\n'
    '            end   = output_str.rfind("}") + 1\n'
    '            if start >= 0 and end > start:\n'
    '                try:\n'
    '                    parsed_data = json.loads(output_str[start:end])\n'
    '                except json.JSONDecodeError:\n'
    '                    print("  Warning: could not parse JSON from parse agent output.")\n'
    '\n'
    '            inv_num = parsed_data.get("invoice_number", "unknown")\n'
    '\n'
    '            # Log ParseCustomerResponse call\n'
    '            _append_agent_log(PARSE_LOG, "ParseCustomerResponse",\n'
    '                              email_file.name, inv_num, parse_input, parse_result)\n'
    '\n'
    '            # ── Step 2: AccessUpdateERP (promise_date emails only) ───────\n'
    '            if parsed_data.get("email_type") == "promise_date":\n'
    '                promise_date = parsed_data.get("promise_date", "")\n'
    '                cust_name    = parsed_data.get("customer_name", "")\n'
    '                erp_input    = (\n'
    '                    f"Update ERP for invoice {inv_num} with promise date {promise_date}. "\n'
    '                    f"Customer: {cust_name}"\n'
    '                )\n'
    '                print(f"  → Promise date detected for {inv_num} — calling AccessUpdateERP")\n'
    '                erp_result = erp_agent.invoke({"messages": [("human", erp_input)]})\n'
    '\n'
    '                # Log AccessUpdateERP call\n'
    '                _append_agent_log(ERP_LOG, "AccessUpdateERP",\n'
    '                                  email_file.name, inv_num, erp_input, erp_result)\n'
    '\n'
    '        except Exception as e:\n'
    '            print(f"  ERROR processing {email_file.name}: {e}")\n'
    '\n'
    '        # Always move the email to Processed_Emails regardless of outcome\n'
    '        dest = PROCESSED_EMAILS_DIR / email_file.name\n'
    '        shutil.move(str(email_file), str(dest))\n'
    '        print(f"  → Moved {email_file.name} to Processed_Emails/")\n'
    '\n'
    "    print(f\"\\n{'=' * 60}\")\n"
    '    print("All emails processed. Orchestration complete.")\n'
    "    print(f\"{'=' * 60}\")"
)

nb["cells"][9]["source"] = new_source

with open("ARDunning.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Cell 9 patched — per-agent logging added to orchestrate().")
